name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: [ubuntu-latest]
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@018abf956a0a15673dae4932ae26f0f071ac0944
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Install Nix Packages
        run: |
          nix-shell --run true

      - name: Check Nix Packages without direnv
        run: |
          set -x
          echo PYTHONPATH=$PYTHONPATH
          which prettier || :

      - name: Install Nix Packages & Export Using direnv
        run: |
          nix-shell --run true
          ./direnv allow
          ./direnv export gha >> "$GITHUB_ENV"

      - name: Check Nix Packages with direnv
        run: |
          set -x
          echo PYTHONPATH=$PYTHONPATH
          which prettier
